export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK'
export const SET_IS_PLAYING = 'SET_IS_PLAYING'
export const SET_CURRENT_TRACKLIST = 'SET_CURRENT_TRACKLIST'

export const SET_IS_LOADING = 'SET_IS_LOADING'
